### ISSUE TITLE
ABI.find_and_decode function doesn't validate input arguments

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/ex_abi#158] opened 2024-01-16 09:29 UTC
Let's consider function ABI like this: `claim()` function wit no arguments

```
abi = %ABI.FunctionSelector{
     function: "claim",
     method_id: <<78, 113, 217, 45>>,
     type: :function,
     inputs_indexed: nil,
     state_mutability: :non_payable,
     input_names: [],
     types: [],
     returns: [],
     return_names: []
   }
```

Shouldn't input data `<<78, 113, 217, 45, 18, 36>>` be considered as wrong input with such ABI since `claim()` method has no arguments and arbitrary `<<18, 36>>` are sent at the end of input data?

The actual response is:
```
iex(2)> ABI.find_and_decode([abi], <<78, 113, 217, 45, 18, 36>>)
{%ABI.FunctionSelector{
   function: "claim",
   method_id: <<78, 113, 217, 45>>,
   type: :function,
   inputs_indexed: nil,
   state_mutability: :non_payable,
   input_names: [],
   types: [],
   returns: [],
   return_names: []
 }, []}
```

**Comment by ayrat555** [comment] 2024-01-31 08:22
@vbaranov will it be possible to share the actual tx to I can investigate?

it seems the issue is similar to https://github.com/poanetwork/ex_abi/issues/156

maybe it makes sense to return error if there is additional input. I will take a look after you send my a tx example

**Comment by vbaranov** [comment] 2024-04-10 11:28
> <<78, 113, 217, 45>>

Sure, e.g. [this one](https://eth-goerli.blockscout.com/tx/0x4672e5b9468a62dbe89480be4aecfe854218c54aee0e45d2f292df7814de7754)

**Comment by ayrat555** [comment] 2024-04-29 06:09
@vbaranov I think it's alright. checked in web3.js

```
let result = web3.eth.abi.decodeParameters([], '0x1224')
> { __length__: 0 }
```

**Closed** 2024-05-02 09:34 UTC
