### ISSUE TITLE
this is issue is comming when i compile the blockscout  code in windows OS

### ISSUE THREAD

**Issue by soumen29121997** [poanetwork/ex_abi#96] opened 2022-04-12 19:37 UTC
@vbaranov 

==> libsecp256k1
could not compile dependency :libsecp256k1, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile libsecp256k1", update it with "mix deps.update libsecp256k1" or clean it with "mix deps.clean libsecp256k1"
** (ErlangError) Erlang error: :enoent
    (elixir 1.13.4) lib/system.ex:1044: System.cmd("make", [], [into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    e:/Phoniex/blockscout-master/deps/libsecp256k1/mix.exs:3: Mix.Tasks.Compile.MakeBindings.run/1
    (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:36: Mix.Tasks.Compile.All.run/1
    (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3

**Comment by ayrat555** [comment] 2022-04-15 08:03
@soumen29121997 hello!

I think the issue is not related to ex_abi?

**Comment by vbaranov** [comment] 2022-04-15 11:21
I suppose it was accidentally opened in ex_abi repository. Resolved in frame of https://github.com/blockscout/blockscout/issues/5453

**Comment by soumen29121997** [comment] 2022-04-18 15:42
@ayrat555 you can check this https://github.com/blockscout/blockscout/issues/5453 your all problem will be resolved

**Closed** 2022-04-19 17:07 UTC
